### ISSUE TITLE
Docker image on Docker Hub, ready to use

### ISSUE THREAD

**Issue by dtitov** [unioslo/tsd-file-api#10]
Hi,

Is it possible to create a ready-to-use Docker image and publish it on Docker Hub? Or even better: set up an automated build that will update this image on incoming changes automatically?

The reason is that I've tried to build it locally, I've got a Docker image built, but then this image doesn't seem to work:
```
Traceback (most recent call last):
  File "tsdfileapi/api.py", line 57, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Also, it would be really nice to have an example for Docker Compose / Docker Swarm.

**Comment by haatveit** [comment]
Hi,

I also think it would be nice to have a Dockerfile available to allow for quickly spinning up a test container, and I guess a Compose file would make sense too with some reference settings prepared.

The error in your traceback comes from lacking PyYAML, which should be available if you install the API's requirements:
https://github.com/unioslo/tsd-file-api/blob/master/README.md#dev-environment

**Comment by dtitov** [comment]
Just to clarify me:
1. `Dockerfile` already exists in the repo. What I meant it that it would be nice to have the built image be published to https://hub.docker.com/ (possibly automatically).
2. This `Dockerfile`, however, seems to be incorrect, because the error above is happening **inside** Docker container. So it's nothing to do with my local PyYAML or any other dependencies...

**Comment by haatveit** [comment]
Hi again,

The `Dockerfile` that is currently in the repo is only intended for creating RPMs of `tsd-file-api` and a `virtualenv` with all of its requirements and is used by the `build.sh` script. It will not produce a container usable for running the API itself.

Thinking about publishing to Dockerhub will have to wait until we have a `Dockerfile` that runs an API instance.

**Comment by dtitov** [comment]
Oh, I see now. Thanks for clarification :)

**Comment by dtitov** [comment]
Hi, any update on this?

**Comment by leondutoit** [comment]
Next important feature to implement is rabbitmq integration. Can look into this after that.
