### ISSUE TITLE
Wrong routing key for MQ messages from FileRequestHandler on survey backend

### ISSUE THREAD

**Issue by leondutoit** [unioslo/tsd-file-api#181]
The [routing key](https://github.com/unioslo/tsd-file-api/blob/738838ddb03970be4961612402fb2fa8d4c9b441/tsdfileapi/api.py#L490) for RabbitMQ messages emitted from the FileRequestHandler use the value of `self.endpoint`, which is [set in the initialize method](https://github.com/unioslo/tsd-file-api/blob/738838ddb03970be4961612402fb2fa8d4c9b441/tsdfileapi/api.py#L1031) of the class. 

[Both uses of the handler for the survey API](https://github.com/unioslo/tsd-file-api/blob/738838ddb03970be4961612402fb2fa8d4c9b441/tsdfileapi/api.py#L2803-L2812) currently set the self.endpoint to `None`, which will result in the wrong routing key.

The fix is to set the value to `survey` instead.

**Comment by haatveit** [comment]
The fix for this was merged in #182 and released as part of [v2.15.1](https://github.com/unioslo/tsd-file-api/releases/tag/v2.15.1).
