### ISSUE TITLE
patch numbering in audits endpoint are not sequential

### ISSUE THREAD

**Issue by drmowinckels** [unioslo/tsd-file-api#187]
I was working with the audit endpoint and am noticing that the numbering of the audits do not actually follow the timestamps of the patches
In my case, I did some patches yesterday on a form, and they were be numbered 145, 146 and 147 in the nettskjema loader webUi.

Then I did some patches today, and now the new patches are 145 146 and 147, while the ones from yesterday are 148 149 150. 

This seems inconsistent to me. A patch should have a permanent number, right? I noticed that the audit endpoint does not actually return the patch number is its payload, but  other markers (which have nice unique and persistent markers of the patch). 

But since the audit endpoint I could see for retrieving information about a specific patch uses the patch number in the url query to retrieve information about it, if this is not a persistent marker of the patch, then this can create some difficulties downstream. 

Likely, the best option here is to have the API number the patch directly, and have the nettskjema loader (webui) display that, rather than relying on the UI (or other interfacing program) number is, as its not sequential.

Here's a screenshot of the two first columns in the nettskjema loader UI Audit section for a form. Notice the two rows where the date is 2023-08-25 in between the 2023-08-24 dates. Meaning the numbering for the audits were altered once I patched this morning.
<img width="386" alt="image" src="https://github.com/unioslo/tsd-file-api/assets/14014329/22633ec2-ac70-498e-8038-378a87c0aa42">

**Comment by leondutoit** [comment]
You're right: there is no "patch number" in the audit data. As such, this is a front-end issue, not an API issue.

**Comment by f-krull** [comment]
good find @drmowinckels 

>  I suggest sending this as an RT to ec-contact.
please don't

@leondutoit what would you suggest to identify an audit entry? timestamp?

**Comment by leondutoit** [comment]
Here is (the definition of audit entries](https://github.com/unioslo/pysquril/blob/b16f2337d70f940a88689f0311d00ad616c9d393/pysquril/backends.py#L75-L86). Timestamps are a natural way of ordering things imo. You decide. Please close the issue when the discussion is done.

**Comment by drmowinckels** [comment]
timestamps seem meaningful in terms of ordering, but imo in terms of accessing a single audit trail (currently through `audit={number}` query) is likely best done through the audits "identity" (which is unique and persistent), but currently not displayed in the webui

**Comment by f-krull** [comment]
> Here is [the definition of audit entries](https://github.com/unioslo/pysquril/blob/b16f2337d70f940a88689f0311d00ad616c9d393/pysquril/backends.py#L75-L86). Timestamps are a natural way of ordering things imo.

I totally agree. That is why I was asking about _identifying_.

**Comment by leondutoit** [comment]
> > Here is [the definition of audit entries](https://github.com/unioslo/pysquril/blob/b16f2337d70f940a88689f0311d00ad616c9d393/pysquril/backends.py#L75-L86). Timestamps are a natural way of ordering things imo.
> 
> I totally agree. That is why I was asking about _identifying_.

Perhaps the linked code was not clear enough, but `event_id` is unique per submission. Note: only audits that were made after https://github.com/unioslo/pysquril/releases/tag/v0.3.6 went into production will have the `event_id` attribute.

**Comment by f-krull** [comment]
Right, `event_id` wasn't available when the audit page was first implemented last September. We should use that.

![Selection_349](https://github.com/unioslo/tsd-file-api/assets/11461352/1614b7fe-9337-494e-806f-0556b1938eaf)

**Comment by drmowinckels** [comment]
sounds good to me.

**Comment by haatveit** [comment]
But perhaps there needs to also be fallback to `timestamp` if `event_id` is missing for older entries.

**Comment by f-krull** [comment]
Yeah. Or they could just be ignored in the UI.

Ideally, older entries would be updated in the DB so that we have homogeneous data. It would reduce complexity of every client using the audits. Not sure if there is hope for that.

**Comment by leondutoit** [comment]
> Yeah. Or they could just be ignored in the UI.
> 
> Ideally, older entries would be updated in the DB so that we have homogeneous data. It would reduce complexity of every client using the audits. Not sure if there is hope for that.

Could be done, but not sure if it is worth it.

**Comment by f-krull** [comment]
Worth the risk or the effort? 

In any case, I hope we can agree the it would reduce tech dept. It's easy to write the UI code to handle both data structures - I'm thinking about maintainability.

**Comment by leondutoit** [comment]
When I said "I'm not sure it is worth it" I meant the following: I'm _not sure_ that any researcher would actually need access to audit records which were written prior to the changes made to the audit records. I didn't mean that I think it is not worth it, I literally meant that I am not sure about it.

That said, it is possible to change the historical data to match the post-change data, save one for attribute that cannot be constructed after the fact: `query`. This refers to the URI query which was used to limit the scope of the update or delete. I estimate about 3 - 4 hours of work (for me) to write something that can transition data. Might take longer for those less familiar with the internals.

**Comment by f-krull** [comment]
I see. How about I rewrite the audit page to only fetch show the new format? We need that anyway. And then we hope no one needs the old entries :)

**Comment by leondutoit** [comment]
I support that. We can notify Nettskjema users about the change before release too. If it turns out to be critical for someone, then it can be fixed within a reasonable time imo.

**Comment by leondutoit** [comment]
Nothing to do in the API, closing.
