### ISSUE TITLE
Remove HNAS backend

### ISSUE THREAD

**Issue by kouylekov-usit** [unioslo/tsd-file-api#224]
We guesstimate that the file API will default back to HNAS-related code path if ESS exhibits write failures. The `tenant_storage_cache` dictionary might be involved. Since `/tsd` is dead anyway, accessing `/tsd` will not work and [import/export etc] will fail.

**Comment by leondutoit** [comment]
Although, I'm puzzled by the behaviour, @uio-torjus addressed this a while ago: https://github.com/unioslo/tsd-file-api/commit/7f888d76ed189d51d211dd9981b4313bc74f900e

**Comment by amn** [comment]
If I were to guess, which admittedly shouldn't be worth much in this context, and yet: there's possibly fallback that functions where `/tsd` is chosen, even with https://github.com/unioslo/tsd-file-api/commit/7f888d76ed189d51d211dd9981b4313bc74f900e. The commit mentions "_Default_ to ESS...", implying it doesn't necessarily disable HNAS. I don't know, just trying to give you some pointers, FWIIW :)

**Comment by leondutoit** [comment]
fwiw, @kouylekov-usit pointed out the likely cause is that the file API looked for the ESS directory during a time when the ESS mounts were not present (due to another problem), and then cached that those projects did not have ESS at all.
